version: 0.1.0.{build}

branches:
  only:
  - master

environment:
  global:
    TARGET: dot 
    TOOLCHAIN: stable
  matrix:
    - HOST: i686-pc-windows-msvc
    - HOST: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/i686-pc-windows-msvc/rustup-init.exe'
  - rustup-init.exe --no-modify-path --default-toolchain=%TOOLCHAIN% --default-host=%HOST% -y --verbose
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if NOT "%HOST%" == "x86_64-pc-windows-msvc" rustup target add %HOST%
  - rustc -V
  - cargo -V

build_script:
  - cargo build --release --target=%HOST%
  - .\ci_deploy.bat

test_script:
  - cargo test --release

artifacts:
  - path: $(TARGET)-$(HOST)

deploy:
  provider: GitHub
  draft: false
  prerelease: false
  force_update: true
  auth_token:
    secure: wf5/9pbr8Jl2sGXJSnm6m9qLT5Xu6cgbXZ8vO+81DnXcCUSvO2hZMW2mCSGNTVqW
  on:
    branch: master
    appveyor_repo_tag: true
