version: 0.1.0.{build}

branches:
  only:
  - master

environment:
  global:
    PKGNAME: dot 
    TOOLCHAIN: stable
  matrix:
    - HOST: i686-pc-windows-msvc
    - HOST: x86_64-pc-windows-msvc

install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/i686-pc-windows-msvc/rustup-init.exe'
  - rustup-init.exe --no-modify-path --default-toolchain=%TOOLCHAIN% --default-host=%HOST% -y --verbose
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --release --target=%HOST%
  - mkdir %PKGNAME%-%HOST%\bin
  - mkdir %PKGNAME%-%HOST%\etc\bash_completion.d
  - mkdir %PKGNAME%-%HOST%\share\zsh\site-functions
  - mkdir %PKGNAME%-%HOST%\share\fish\completions
  - copy target\%HOST%\release\%PKGNAME%.exe   .\%PKGNAME%-%HOST%\bin\%PKGNAME%.exe
  - copy completions\%PKGNAME%.bash-completion .\%PKGNAME%-%HOST%\etc\bash_completion.d\%PKGNAME%
  - copy completions\_%PKGNAME%                .\%PKGNAME%-%HOST%\share\zsh\site-functions\_%PKGNAME%
  - copy completions\%PKGNAME%.fish            .\%PKGNAME%-%HOST%\share\fish\completions\%PKGNAME%.fish

test_script:
  - cargo test --release --target=%HOST%

artifacts:
  - path: $(PKGNAME)-$(HOST)

deploy:
  provider: GitHub
  draft: false
  prerelease: false
  force_update: true
  auth_token:
    secure: wf5/9pbr8Jl2sGXJSnm6m9qLT5Xu6cgbXZ8vO+81DnXcCUSvO2hZMW2mCSGNTVqW
  on:
    branch: master
    appveyor_repo_tag: true
