[package]
name = "dot"
version = "0.3.0"
authors = ["Greg Orzell", "Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
description = "Alternative of dotfile management frameworks"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = { version = "3.0.0-rc.11", features = ["derive", "wrap_help"] }
clap_generate = "3.0.0-rc.11"
error-chain = "0.12"
regex = "1.5"
shellexpand = "2"
toml = "0.5"
url = "2.2"
dirs = "4.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
advapi32-sys = "0.2"
kernel32-sys = "0.2"
runas = "0.2"
