[package]
name = "dot"
version = "0.1.3"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
description = "Alternative of dotfile management frameworks"

[build-dependencies]
clap = "^2.16.0"

[dependencies]
clap = "^2.20.3"
toml = "^0.2.1"
shellexpand = "^1.0.0"
ansi_term = "^0.9.0"
regex = "^0.2.1"
url = "^1.4.0"
error-chain = "^0.9.0"

[target.'cfg(windows)'.dependencies]
winapi = "^0.2.8"
advapi32-sys = "^0.2.0"
kernel32-sys = "^0.2.2"
runas = "^0.1.1"
