[package]
name = "dot"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
description = "Alternative of dotfile management frameworks"
build = "build.rs"

[build-dependencies]
clap = "^2.16.0"

[dependencies]
clap = "^2.16.2"
toml = "^0.2.1"
shellexpand = "0.1.0"
ansi_term = "^0.9.0"
#regex = "^0.1.77"
winapi = "^0.2.8"
advapi32-sys = "^0.2.0"
kernel32-sys = "^0.2.2"
runas = "^0.1.1"
