[package]
name = "dot"
version = "0.1.4"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
description = "Alternative of dotfile management frameworks"
edition = "2018"

[dependencies]
ansi_term = "0.12"
clap = "2.20"
error-chain = "0.12.1"
regex = "1.4.3"
shellexpand = "2"
toml = "0.5"
url = "2.2"
dirs = "3.0.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
advapi32-sys = "0.2.0"
kernel32-sys = "0.2.2"
runas = "0.2.1"
