"tmux.conf"     = "~/.tmux.conf"
gitconfig       = "~/.gitconfig"
tigrc           = "~/.tigrc"
zsh             = "~/.config/zsh"
"zsh/zshenv"    = "~/.zshenv"
"zsh/zshrc"     = "~/.zshrc"
vim             = "~/.config/vim"
"vim/vimrc"     = "~/.vimrc"
"vim/gvimrc"    = "~/.gvimrc"
